language: node_js
node_js:
- '8'
sudo: required
services:
- docker

jobs:
  include:
    - after_deploy:
           - echo "done deploying"
    - stage: deploy
      deploy:
          provider: elasticbeanstalk
	  app: $ebapp
          env: $ebenv
          bucket_name: travistest-eu-west-2-test
          on:
           branch: master                       
